### ISSUE TITLE
I'd like to contribute i18n translations, but make i18n doesn't work

### ISSUE THREAD

**Issue by fredvd** [eea/volto-accordion-block#111]
make i18n assumes there is a local node modules installed, but most other make command and make install build docker containers/use docker compose.  How can I contribute an extra set of locales? (for Dutch/NL)

**Comment by stevepiercy** [comment]
https://github.com/eea/volto-accordion-block/blob/master/DEVELOP.md refers to old Volto docs, which are now https://6.docs.plone.org/volto/contributing/developing-core.html, https://6.docs.plone.org/i18n-l10n/contributing-translations.html#translate-volto, and https://6.docs.plone.org/volto/development/i18n.html.

**Comment by erral** [comment]
Create the `nl/LC_MESSAGES/` folder, copy over the `volto.pot` file there as `volto.po` and contribute the translations.

When the addon will be installed in a given frontend, is frontend's task to run `yarn i18n` and collect the translations from the addons.

**Comment by stevepiercy** [comment]
Here it is in the docs, Internationalization and Localization > [Translate Volto](https://6.docs.plone.org/i18n-l10n/contributing-translations.html#translate-volto). LOL, @erral I should read [what we collaborated on 2 years ago](https://github.com/plone/documentation/blame/6.0/docs/i18n-l10n/contributing-translations.md#L63-L81) more carefully!

However, I think the following docs updates would help developers navigate to the right location.

- Frontend > Development > [Contribute translations for an unsupported language](https://6.docs.plone.org/volto/development/i18n.html#contribute-translations-for-an-unsupported-language) is not helpful, but should point to [Translate Volto](https://6.docs.plone.org/i18n-l10n/contributing-translations.html#translate-volto).
- https://github.com/eea/volto-accordion-block/blob/master/DEVELOP.md should be updated with links to current development practices, and a new heading added for contributing translations with a link to the Translate Volto docs.
- @erral's comment should go in Translate Volto docs.

Does all that sound correct? If so, then I can do the docs updates in various repos and PRs. Please let me know. Thank you!

**Comment by stevepiercy** [comment]
I created the 3 PRs. After they are all merged, then this issue can be closed.

- https://github.com/eea/volto-accordion-block/pull/114
- https://github.com/plone/documentation/pull/1737
- https://github.com/plone/volto/pull/6386

**Comment by avoinea** [comment]
@fredvd @stevepiercy Merged and released

**Comment by stevepiercy** [comment]
@avoinea thank you!

@fredvd I think you can you close this issue now.

**Comment by fredvd** [comment]
Check! Thanks eveybody
