### ISSUE TITLE
BlockChooser - showRestricted - should come from configs

### ISSUE THREAD

**Issue by claudiaifrim** [eea/volto-accordion-block#77]
Considering [this](https://github.com/eea/volto-accordion-block/commit/bdf3e97fac92c130f43c03e610e530f41dd5bc17#diff-34189ed85b8cebc07a522ae42c2d4891e03dab839f1e79376b0c3d468d32bc5aR30) way of using  showRestricted, it looks like in the accordion block we have this issue:
![image](https://github.com/eea/volto-accordion-block/assets/4428527/ed8202f5-afd7-4733-b0ec-9b50ad8301f4)

![image](https://github.com/eea/volto-accordion-block/assets/4428527/e2e688fc-a38f-4db7-a11a-57454d20bd2b)

showRestricted should come from configs

**Comment by avoinea** [comment]
Merged
