### ISSUE TITLE
Permission to create a Pr directly in repo.

### ISSUE THREAD

**Issue by iFlameing** [eea/volto-accordion-block#84]
@avoinea @tiberiuichim @alecghica I don't think I have permission to push directly to the repo. Can you please give me permission to so that I can open pr for translation fixes?

**Comment by tiberiuichim** [comment]
@iFlameing send the PR from a fork, and we'll merge. I'm not sure about the organisational implications of granting permissions to these repos to non-EEA consultants.

**Comment by ichim-david** [comment]
Closing issue as you can simply fork and send a pull request from the fork as mentioned by @tiberiuichim
